import {
  BASE_ACTION_INTERVAL,
  INTERACTION_RANGE,
  MOVE_VECTOR_FORWARD,
  MOVE_VECTOR_RIGHT,
  PLAYER_BASE_MOVE_SPEED,
  SPRINT_MULTIPLIER,
  WORLD_LIMIT,
} from "@shared/constants/gameplay.js";

export {
  BASE_ACTION_INTERVAL,
  INTERACTION_RANGE,
  MOVE_VECTOR_FORWARD,
  MOVE_VECTOR_RIGHT,
  PLAYER_BASE_MOVE_SPEED,
  SPRINT_MULTIPLIER,
  WORLD_LIMIT,
};

export const ISO_FRUSTUM = 22;
export const CAMERA_OFFSET = Object.freeze([16, 18, 16]);
export const CAMERA_DEAD_ZONE = 2.8;
